"""Add remaining supabase tables

Revision ID: 0fad00ebebcc
Revises: 81e1f7b12513
Create Date: 2026-02-24 01:21:34.315747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0fad00ebebcc'
down_revision: Union[str, Sequence[str], None] = '81e1f7b12513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_competencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cbe_category', sa.String(), nullable=False),
    sa.Column('departments', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_competencies_id'), 'master_competencies', ['id'], unique=False)
    op.create_table('game_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_prompt', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('custom_game_url', sa.String(), nullable=True),
    sa.Column('cover_photo_url', sa.String(), nullable=True),
    sa.Column('preview_image', sa.String(), nullable=True),
    sa.Column('game_config', sa.JSON(), nullable=False),
    sa.Column('design_settings', sa.JSON(), nullable=True),
    sa.Column('selected_sub_competencies', sa.JSON(), nullable=True),
    sa.Column('competency_id', sa.String(), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['master_competencies.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_templates_id'), 'game_templates', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('company_logo_url', sa.String(), nullable=True),
    sa.Column('game_avatar_url', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('design_palette', sa.JSON(), nullable=True),
    sa.Column('default_particle_effect', sa.String(), nullable=True),
    sa.Column('mascot_animation_type', sa.String(), nullable=True),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('sub_competencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('competency_id', sa.String(), nullable=True),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('action_cue', sa.String(), nullable=True),
    sa.Column('game_loop', sa.String(), nullable=True),
    sa.Column('game_mechanic', sa.String(), nullable=True),
    sa.Column('player_action', sa.String(), nullable=True),
    sa.Column('validator_type', sa.String(), nullable=True),
    sa.Column('scoring_formula_level_1', sa.String(), nullable=True),
    sa.Column('scoring_formula_level_2', sa.String(), nullable=True),
    sa.Column('scoring_formula_level_3', sa.String(), nullable=True),
    sa.Column('scoring_logic', sa.JSON(), nullable=True),
    sa.Column('backend_data_captured', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['master_competencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_competencies_id'), 'sub_competencies', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('brand_customizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('unique_code', sa.String(), nullable=True),
    sa.Column('customization_prompt', sa.Text(), nullable=True),
    sa.Column('generated_game_html', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.Column('accent_color', sa.String(), nullable=True),
    sa.Column('background_color', sa.String(), nullable=True),
    sa.Column('highlight_color', sa.String(), nullable=True),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.Column('font_family', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('cover_photo_url', sa.String(), nullable=True),
    sa.Column('particle_effect', sa.String(), nullable=True),
    sa.Column('mascot_animation_type', sa.String(), nullable=True),
    sa.Column('custom_config', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('live_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('live_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['game_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_code')
    )
    op.create_index(op.f('ix_brand_customizations_id'), 'brand_customizations', ['id'], unique=False)
    op.create_table('validator_test_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('sub_competency_id', sa.String(), nullable=True),
    sa.Column('tester_id', sa.String(), nullable=True),
    sa.Column('template_type', sa.String(), nullable=False),
    sa.Column('test_version', sa.String(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=True),
    sa.Column('approved_for_publish', sa.Boolean(), nullable=True),
    sa.Column('phase1_status', sa.String(), nullable=True),
    sa.Column('phase1_notes', sa.Text(), nullable=True),
    sa.Column('phase1_checklist', sa.JSON(), nullable=True),
    sa.Column('phase2_status', sa.String(), nullable=True),
    sa.Column('phase2_notes', sa.Text(), nullable=True),
    sa.Column('phase3_status', sa.String(), nullable=True),
    sa.Column('phase3_notes', sa.Text(), nullable=True),
    sa.Column('phase3_test_runs', sa.JSON(), nullable=True),
    sa.Column('v3_1_check_results', sa.JSON(), nullable=True),
    sa.Column('backend_data_captured', sa.JSON(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sub_competency_id'], ['sub_competencies.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['game_templates.id'], ),
    sa.ForeignKeyConstraint(['tester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validator_test_results_id'), 'validator_test_results', ['id'], unique=False)
    op.create_table('validators_runtime',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('feedback_mode', sa.String(), nullable=False),
    sa.Column('attempts', sa.String(), nullable=False),
    sa.Column('time_limit_s', sa.Integer(), nullable=True),
    sa.Column('sessions_required', sa.Integer(), nullable=True),
    sa.Column('accuracy_threshold', sa.Float(), nullable=True),
    sa.Column('edge_threshold', sa.Float(), nullable=True),
    sa.Column('proof_log', sa.Boolean(), nullable=True),
    sa.Column('randomize', sa.Boolean(), nullable=True),
    sa.Column('seed', sa.String(), nullable=True),
    sa.Column('ui_theme', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['game_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validators_runtime_id'), 'validators_runtime', ['id'], unique=False)
    op.create_table('game_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('customization_id', sa.String(), nullable=True),
    sa.Column('competency_id', sa.String(), nullable=True),
    sa.Column('sub_competency_id', sa.String(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('proficiency_level', sa.String(), nullable=True),
    sa.Column('scoring_metrics', sa.JSON(), nullable=False),
    sa.Column('gameplay_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['master_competencies.id'], ),
    sa.ForeignKeyConstraint(['customization_id'], ['brand_customizations.id'], ),
    sa.ForeignKeyConstraint(['sub_competency_id'], ['sub_competencies.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['game_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_results_id'), 'game_results', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('runtime_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('edge_score', sa.Float(), nullable=True),
    sa.Column('time_s', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['runtime_id'], ['validators_runtime.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('content', sqlite.JSON(), nullable=True),
    sa.Column('creator_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_game_results_id'), table_name='game_results')
    op.drop_table('game_results')
    op.drop_index(op.f('ix_validators_runtime_id'), table_name='validators_runtime')
    op.drop_table('validators_runtime')
    op.drop_index(op.f('ix_validator_test_results_id'), table_name='validator_test_results')
    op.drop_table('validator_test_results')
    op.drop_index(op.f('ix_brand_customizations_id'), table_name='brand_customizations')
    op.drop_table('brand_customizations')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sub_competencies_id'), table_name='sub_competencies')
    op.drop_table('sub_competencies')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_game_templates_id'), table_name='game_templates')
    op.drop_table('game_templates')
    op.drop_index(op.f('ix_master_competencies_id'), table_name='master_competencies')
    op.drop_table('master_competencies')
    # ### end Alembic commands ###
