-- Re-insert the deleted Analytical Thinking sub-competencies
INSERT INTO public.sub_competencies (
  id,
  competency_id,
  statement,
  player_action,
  backend_data_captured,
  scoring_logic,
  display_order,
  validator_type,
  action_cue,
  game_mechanic,
  scoring_formula_level_1,
  scoring_formula_level_2,
  scoring_formula_level_3,
  game_loop
) VALUES
(
  'daacd6fe-2c23-43fd-a640-5a12d3e09855',
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'Distinguish valid solutions under incomplete or contradictory inputs',
  'Player flags missing data and selects consistent plan.',
  '["missing_flags_correct_pct", "solution_valid", "conflict_resolve_time_ms"]'::jsonb,
  '{"formula": "Accuracy = % missing_flags correct ≥ 85 AND solution_valid = 1; Time ≤ 90 s; Edge = Conflict Resolved ≤ 8 s", "time_limit_s": 90, "edge_resolve_s": 8, "accuracy_threshold": 0.85}'::jsonb,
  3,
  'Data Analysis',
  'Infer best solution when key data is missing or conflicting.',
  'Error-Detection / Diagnosis Task (diagnostic assessment)',
  '<80',
  '80–94',
  '≥95 + Edge',
  'Scan data → Flag issues → Select solution → Confirm → Feedback'
),
(
  '7c8d9e0f-1a2b-3c4d-5e6f-7a8b9c0d1e2f',
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'Evaluate claims against evidence and identify logical gaps',
  'Player marks inconsistent claims and selects strongest evidence.',
  '["claims_evaluated", "logical_gaps_identified", "evidence_strength_score"]'::jsonb,
  '{"formula": "Accuracy = % claims correct ≥ 80 AND gaps_found ≥ 2; Time ≤ 120 s; Edge = Reversal Justified ≤ 10 s", "time_limit_s": 120, "edge_resolve_s": 10, "accuracy_threshold": 0.80}'::jsonb,
  1,
  'Argument Mapping',
  'Spot weak reasoning and verify supporting data.',
  'Debate / Argument Evaluation (persuasive assessment)',
  '<75',
  '75–89',
  '≥90 + Edge',
  'Read claim → Check evidence → Flag gaps → Rank strength → Confirm'
),
(
  '3f4e5d6c-7b8a-9c0d-1e2f-3a4b5c6d7e8f',
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'Break down complex problems into manageable sub-tasks',
  'Player decomposes problem and orders subtasks logically.',
  '["subtasks_identified", "sequence_correct", "decomposition_time_ms"]'::jsonb,
  '{"formula": "Accuracy = % subtasks correct ≥ 85 AND sequence valid; Time ≤ 100 s; Edge = Re-sequence ≤ 12 s", "time_limit_s": 100, "edge_resolve_s": 12, "accuracy_threshold": 0.85}'::jsonb,
  2,
  'Task Decomposition',
  'Identify steps to solve a multi-part challenge.',
  'Sequencing / Ordering Task (structural assessment)',
  '<80',
  '80–92',
  '≥93 + Edge',
  'View problem → Identify parts → Order steps → Validate → Submit'
),
(
  '9a0b1c2d-3e4f-5a6b-7c8d-9e0f1a2b3c4d',
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'Recognize patterns and trends in data sets',
  'Player identifies recurring patterns and forecasts next step.',
  '["patterns_found", "forecast_accuracy", "pattern_type"]'::jsonb,
  '{"formula": "Accuracy = % patterns correct ≥ 80 AND forecast valid; Time ≤ 90 s; Edge = Pattern Shift ≤ 8 s", "time_limit_s": 90, "edge_resolve_s": 8, "accuracy_threshold": 0.80}'::jsonb,
  4,
  'Pattern Recognition',
  'Spot trends and predict what comes next.',
  'Pattern Matching / Prediction (analytical assessment)',
  '<75',
  '75–88',
  '≥89 + Edge',
  'Scan data → Find pattern → Predict next → Confirm → Feedback'
),
(
  '5b6c7d8e-9f0a-1b2c-3d4e-5f6a7b8c9d0e',
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'Apply structured frameworks to solve ambiguous problems',
  'Player selects framework and applies it step-by-step.',
  '["framework_selected", "steps_completed", "solution_quality"]'::jsonb,
  '{"formula": "Accuracy = framework appropriate AND steps ≥ 3 correct; Time ≤ 120 s; Edge = Framework Pivot ≤ 15 s", "time_limit_s": 120, "edge_resolve_s": 15, "accuracy_threshold": 0.75}'::jsonb,
  5,
  'Framework Application',
  'Choose and apply the right mental model.',
  'Decision Tree / Scenario Analysis (strategic assessment)',
  '<70',
  '70–85',
  '≥86 + Edge',
  'Read scenario → Pick framework → Apply steps → Evaluate → Submit'
),
(
  '1c2d3e4f-5a6b-7c8d-9e0f-1a2b3c4d5e6f',
  'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  'Synthesize insights from multiple sources into a cohesive conclusion',
  'Player reviews sources and creates unified insight.',
  '["sources_reviewed", "insight_quality", "synthesis_time_ms"]'::jsonb,
  '{"formula": "Accuracy = sources integrated ≥ 3 AND insight coherent; Time ≤ 150 s; Edge = New Source ≤ 20 s", "time_limit_s": 150, "edge_resolve_s": 20, "accuracy_threshold": 0.80}'::jsonb,
  6,
  'Information Synthesis',
  'Combine separate pieces into one clear takeaway.',
  'Research / Integration Task (integrative assessment)',
  '<75',
  '75–90',
  '≥91 + Edge',
  'Read sources → Identify themes → Combine insights → Write conclusion → Submit'
);